# Generated by Django 3.2.5 on 2022-01-11 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='url',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
